[package]
name = "luma"
version = "0.0.0"
edition = "2024"

[lib]
name = "luma"
path = "src/lib.rs"

[dependencies]
chumsky = "0.11.2"
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5.0"
reqwest = { version = "0.12", features = ["blocking"] }
zip = "2.1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "user-hooks"]
